In [1]:
import pandas as pd
import huggingface_hub
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_parquet(r"F:\AL ML project\AIML\Miniproject2\train-00006.parquet")

In [3]:
print(df.head())

      symbol                 timestamp        open        high         low  \
0  SMARTLINK 2023-12-26 05:37:00+00:00  171.500000  171.500000  171.500000
1  SMARTLINK 2023-12-26 05:39:00+00:00  171.500000  171.500000  171.500000
2  SMARTLINK 2023-12-26 05:43:00+00:00  171.500000  171.500000  171.500000
3  SMARTLINK 2023-12-26 05:48:00+00:00  171.500000  171.500000  170.699997
4  SMARTLINK 2023-12-26 05:49:00+00:00  170.699997  170.699997  170.699997

        close  volume  oi
0  171.500000       0   0
1  171.500000       0   0
2  171.500000       0   0
3  170.699997      50   0
4  170.699997       0   0

In [4]:
#df.to_csv(r"F:\AL ML project\AIML\Miniproject2\train-00006.csv", index=False)
#print("Successfully converted to CSV")

In [5]:
df =pd.read_csv(r"F:\AL ML project\AIML\Miniproject2\train-00006.csv")

In [6]:
df

,symbol,timestamp,open,high,low,close,volume,oi
0,SMARTLINK,2023-12-26 05:37:00+00:00,171.5,171.5,171.5,171.5,0,0
1,SMARTLINK,2023-12-26 05:39:00+00:00,171.5,171.5,171.5,171.5,0,0
2,SMARTLINK,2023-12-26 05:43:00+00:00,171.5,171.5,171.5,171.5,0,0
3,SMARTLINK,2023-12-26 05:48:00+00:00,171.5,171.5,170.7,170.7,50,0
4,SMARTLINK,2023-12-26 05:49:00+00:00,170.7,170.7,170.7,170.7,0,0
...,...,...,...,...,...,...,...,...
44037355,TECILCHEM,2023-05-04 03:46:00+00:00,33.7,33.7,33.7,33.7,250,0
44037356,TECILCHEM,2023-05-04 03:47:00+00:00,33.7,33.7,33.7,33.7,0,0
44037357,TECILCHEM,2023-05-04 03:48:00+00:00,33.7,33.7,33.7,33.7,0,0
44037358,TECILCHEM,2023-05-04 03:49:00+00:00,33.7,33.7,33.7,33.7,0,0
44037359,TECILCHEM,2023-05-04 03:51:00+00:00,33.7,33.7,33.7,33.7,0,0

In [7]:
df.shape

(44037360, 8)

In [8]:
df["target"] = df.groupby("symbol")["close"].shift(-1)

In [9]:
df.shape

(44037360, 9)

In [ ]:
chunk_size = 1_000_000

for i, chunk in enumerate(pd.read_csv("train-00006.csv", chunksize=chunk_size)):
    chunk.to_csv(f"dataset_chunk_{i+1}.csv", index=False)

print("Dataset split successfully!")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44037360 entries, 0 to 44037359
Data columns (total 9 columns):
 #   Column     Dtype
---  ------     -----
 0   symbol     object
 1   timestamp  object
 2   open       float64
 3   high       float64
 4   low        float64
 5   close      float64
 6   volume     int64
 7   oi         int64
 8   target     float64
dtypes: float64(5), int64(2), object(2)
memory usage: 3.0+ GB

In [ ]:
df.describe()

,open,high,low,close,volume,oi,target
count,4.403736e+07,4.403736e+07,4.403736e+07,4.403736e+07,4.403736e+07,44037360.0,4.403721e+07
mean,8.047054e+02,8.051350e+02,8.042536e+02,8.047019e+02,6.120530e+03,0.0,8.047026e+02
std,1.586722e+03,1.587489e+03,1.585920e+03,1.586713e+03,8.760334e+04,0.0,1.586714e+03
min,1.450000e+00,1.470000e+00,1.400000e+00,1.430000e+00,-8.943300e+04,0.0,1.430000e+00
25%,1.042000e+02,1.042500e+02,1.041000e+02,1.041900e+02,0.000000e+00,0.0,1.041900e+02
50%,3.351500e+02,3.354000e+02,3.350000e+02,3.351500e+02,7.600000e+01,0.0,3.351500e+02
75%,7.799500e+02,7.800000e+02,7.794500e+02,7.799500e+02,7.960000e+02,0.0,7.799500e+02
max,1.948445e+04,1.979195e+04,1.935960e+04,1.945570e+04,5.285915e+07,0.0,1.945570e+04

In [ ]:
df.isnull().sum()

symbol         0
timestamp      0
open           0
high           0
low            0
close          0
volume         0
oi             0
target       152
dtype: int64

In [ ]:
print("\nDuplicate rows:", df.duplicated().sum())

Duplicate rows: 0